# Generated by Django 3.0 on 2020-08-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='lga',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
